### ISSUE TITLE
App Rejected: social media features not implemented 

### ISSUE THREAD

**Issue by moorea** [TruckMuncher/TruckMuncher-iOS#24]
The application will not make it through the Apple Review process unless we actually make use of some social media features. Using Facebook and/or Twitter for authentication only is apparently not sufficient. 

According to Apples documentation, "Applications cannot require user registration prior to allowing access to app features and content; such user registration must be optional and tied to account-based functionality"

**Comment by jault3** [comment]
This functionality has been added via https://github.com/TruckMuncher/TruckMuncher-iOS/pull/31 and again extended via https://github.com/TruckMuncher/TruckMuncher-iOS/pull/35. Ready for another submission
